// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import ReduxWrapper from "@/components/ReduxWrapper";
import ReduxPersistWrapper from "../components/ReduxPersistWrapper";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bishal Ghale",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxWrapper>
          <ReduxPersistWrapper>
            <SessionWrapper>
              <Toaster position="top-right" richColors />
              {children}
            </SessionWrapper>
          </ReduxPersistWrapper>
        </ReduxWrapper>
      </body>
    </html>
  );
}
