// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import ReduxPersistWrapper from "../components/ReduxPersistWrapper";
import { Toaster } from "sonner";
import StoreProvider from "@/components/StoreProvider";
import NavLayout from "@/components/home/NavLayout";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bishal Ghale",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ReduxPersistWrapper>
            <SessionWrapper>
              <NavLayout>
                <Toaster position="top-right" richColors />
                <ToastContainer position="top-right" autoClose={3000} />
                {children}
              </NavLayout>
            </SessionWrapper>
          </ReduxPersistWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
